version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  create-env-var:
    executor: basic
    steps:
      - checkout
      - run: 
          name: create env var
          command: |
            echo "export VERSION_NUMBER="hellowolr"" >> $BASH_ENV
            cp "$BASH_ENV" bash.env
      - run: 
          name: create env var 2
          command: |
            cat bash.env >> $BASH_ENV
            echo ${VERSION_NUMBER}
      - run: 
          name: create env var 3
          command: |
            pwd 
            ls
            cd react-app
            ls

workflows:
  main:
    jobs:
      - create-env-var