version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  create-env-var:
    executor: basic
    steps:
      - checkout
      - run: |
          echo "VERSION_NUMBER=20.0.0" >> $BASH_ENV
          mkdir -p packages
          cp $BASH_ENV packages/bash.env
          echo ${VERSION_NUMBER}
      - run: |
          echo "export FOO=BAR" >> $BASH_ENV

      - persist_to_workspace:
          root: packages
          paths:
            - .
  load-env-var:
    executor: basic
    steps:
      - attach_workspace:
          at: packages
      - run: |
          cd packages
          cat bash.env >> $BASH_ENV
      - run: |
          # verify; this should print 'BAR'
          cat $BASH_ENV | grep VERSION_NUMBER

workflows:
  main:
    jobs:
      - create-env-var
      - load-env-var:
          requires:
            - create-env-var