version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  create-env-var:
    executor: basic
    steps:
      - checkout
      - run: 
          name: create env var
          command: |
            ls
            pwd
      - run: 
          name: create env var 2
          command: |
            echo "export VERSION_NUMBER=20.0.0" >> $BASH_ENV
            ls
            mkdir -p packages
            cp $BASH_ENV packages/bash.env
            echo ${VERSION_NUMBER}
      - run: 
          name: create env var 3
          command: |
              ls
              pwd
              cat $BASH_ENV
              echo ${VERSION_NUMBER}
              echo "export FOO=BAR" >> $BASH_ENV
          

      - persist_to_workspace:
          root: packages
          paths:
            - bash.env
  load-env-var:
    executor: basic
    steps:
      - checkout
      - attach_workspace:
          at: packages
      - run: |
          source bash.env 
          echo ${VERSION_NUMBER}
      - run: |
          # verify; this should print 'BAR'
          cat $BASH_ENV | grep VERSION_NUMBER

workflows:
  main:
    jobs:
      - create-env-var
      - load-env-var:
          requires:
            - create-env-var